baseURL: https://antoniosbarotsis.github.io/Blog/
languageCode: en-us
title: My Blog
theme: "PaperMod"
paginate: 5

minify:
    disableXML: true
    minifyOutput: true

markup:
    highlight:
        # anchorLineNos: true
        codeFences: true
        guessSyntax: true
        # lineNos: true
        # noClasses: false
        pygmentsUseClasses: true
        pygmentsCodefences: true
        style: monokai
    goldmark:
        renderer:
             unsafe: true

security:
  funcs:
    getenv:
      - ^HUGO_
      - ^WC_
      - ^BLOGDOWN

params:
    assets:
        disableHLJS: true
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Welcome to my programming Blog!"
    author: Antonios Barotsis
    # author: ["Me", "You"] # multiple authors
    disableThemeToggle: true
    defaultTheme: dark
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowFullTextinRSS: true
    ShowToc: true
    comments: true
    images: ["papermod-cover.png"]

    homeInfoParams:
        Title: "Antonios Barotsis"
        Content: >
            Welcome to my blog!
            I will use this to post articles I write about programming. 
            You can find the code for this repository [here](https://github.com/AntoniosBarotsis/Blog),
            feel free to open an issues with suggestions or corrections!

    socialIcons:
        - name: github
          url: "https://github.com/AntoniosBarotsis"
        - name: twitter
          url: "https://twitter.com/Tony_Barotsis"
        - name: linkedin
          url: "https://www.linkedin.com/in/antonios-barotsis-5a26a0199/"
        - name: "rss"
          url: "https://antoniosbarotsis.github.io/Blog/index.xml"
        # - name: KoFi
        #   url: "https://ko-fi.com/adityatelange"
        # - name: RsS
        #   url: "index.xml"

    editPost:
        URL: "https://github.com/AntoniosBarotsis/Blog/tree/master/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

menu:
    main:
        - identifier: search
          name: Search
          url: /search/
          weight: 1
        - identifier: categories
          name: Categories
          url: /categories/
          weight: 2
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 3
        # - identifier: example
        #   name: example.org
        #   url: https://example.org
        #   weight: 30

outputs:
    home:
        - HTML
        - RSS
        - JSON

taxonomies:
    search: search
    category: Categories
    tag: Tags
