name: github pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.87.0'
      
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("rmarkdown","blogdown"))'
      - name: Install used packages CRAN
        run: Rscript -e 'install.packages(c("devtools", "tidytuesdayR", "tidyverse", "tidymodels", "ggridges", "lubridate", "plotly", "ranger", "kernlab"))'
      - name: Install used packages Github
        run: Rscript -e 'devtools::install_github("Mikata-Project/ggthemr", auth_token = "${{ secrets.PAT }}")'
      - name: Render Book
        run: Rscript -e 'blogdown::build_site(local = FALSE, run_hugo = TRUE, build_rmd = TRUE)'

      - name : Move hardcoded search file
        run: mv public/search .

      - name: Build
        run: hugo --minify

      - name: Replace search file
        run: rm -rf public/search && mv search public && cat public/search/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public